(require 'cl-lib)
(add-to-list 'load-path "~/.emacs.d/lisp")
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes")
; do not forget this step.
(package-initialize)
(require 'defuns)
(require 'god-kmacro)
(set-archives)


(package-initialize)
(setq-config)
(sensible-aliases)
(sensible-defaults)
(load-modes)
(load-optional-modes)
(recentf-mode +1)
(global-set-key (kbd "C-h") (god-extension-set-mode "enable god mode" t))
(global-set-key (kbd "C-c h") (lookup-key global-map (kbd "<f1>")))
(define-key god-local-mode-map (kbd "i") (god-extension-set-mode "disable god mode" nil))
(define-key god-local-mode-map (kbd "S") 'save-buffer)
(define-key god-local-mode-map (kbd "F") 'find-file)
(define-key god-local-mode-map (kbd "V") 'scroll-down-command)
(sensible-modes)