(require 'cl-lib)
(add-to-list 'load-path "~/.emacs.d/lisp")
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes")
; do not forget this step.
(package-initialize)
(require 'defuns)
(set-archives)
(require 'simple-modal)
(require 'ace-jump-mode)
(require 'paredit)
(require 'window-number)
(require 'recentf)

(package-initialize)
(setq-config)
(sensible-aliases)
(sensible-defaults)
(load-modes)
(load-optional-modes)
(recentf-mode +1)
(expression-navigation)
(ratpoison-compat)

(global-set-key (kbd "C-t") 'previous-line)
(global-set-key (kbd "C-p") 'transpose-chars)

(global-set-key (kbd "C-.") 'repeat)
(global-set-key (kbd "C-h") 'simple-modal-mode)
(global-set-key (kbd "C-c h") (lookup-key global-map (kbd "<f1>")))
(sensible-modes)
